### ISSUE TITLE
enable travis

### ISSUE THREAD

**Issue by jhpoelen** [cboettig/contenturi#10]
I tried to enable travis, but got:

```
$ travis enable
not allowed to update service hook for cboettig/contenturi
```

**Comment by jhpoelen** [comment]
@cboettig thanks for enabling travis.

**Comment by cboettig** [comment]
@jhpoelen I'm fine with enabling travis, but note we already have continuous integration set up here via GitHub Actions: https://github.com/cboettig/contenturi/actions, which likewise integrate into PRs: https://github.com/cboettig/contenturi/pull/9/checks

**Comment by jhpoelen** [comment]
Ah cool! I was not familiar with that. Who's running this? Github?

**Comment by cboettig** [comment]
Yup. GitHub launched GitHub Actions out of beta last fall, https://github.com/features/actions (probably by way of catching up with GitLab, where similar stuff has been available for a while).  It is rather nicely done though; in many ways cleaner than doing things with Travis (e.g. one less auth step, and can be great for actions that aren't strictly CI tasks).  (Another advantage is that it makes it easy to test on Windows, which probably isn't necessary for us but a nice step given how clumsy appveyor always felt.  Given GitHub's parent company now I suppose it would be embarrassing if they didn't come up with that!)

Among other things, it has a nice model for writing extensions.  The rstudio team (mostly Jim Hester I think) has implemented a variety of common actions for R: https://github.com/r-lib/actions.  Many of these can be added automatically to a repo using `devtools` & `usethis`, similar to how we usually add travis infrastructure.

**Comment by jhpoelen** [comment]
Nice! Thanks for the details. Do you mind keeping travis around until I catch up with Github actions?
